name: Build & upload toolchain
on:
  push:
  schedule:
    # 3 PM PST on Saturdays
    - cron: "0 22 * * SAT"

jobs:
  build-first:
    runs-on: ubuntu-latest
    steps:
      - name: Setup depends
        env:
          DEBIAN_FRONTEND: "noninteractive"
        run: |
          sudo -E apt update
          sudo -E apt install -y cmake ninja-build libelf-dev patchelf libeatmydata1
          wget -q https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.zip
          unzip master.zip && rm master.zip
          sudo cp -r proton-clang-master/* /usr && rm -r proton-clang-master

      - name: Download scripts
        uses: actions/checkout@v2

      - name: Build toolchain
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          LD_PRELOAD: "/usr/lib/x86_64-linux-gnu/libeatmydata.so"
        run: ./build-toolchain.sh -s 1

      - name: Pass cache to next stage
        uses: actions/cache@v2
        with:
          path: build/llvm/stage1
          key: ${{ runner.os }}-stage1-${{ github.run_id }}

  build-second-1:
    needs: build-first
    runs-on: ubuntu-latest
    steps:
      - name: Setup depends
        env:
          DEBIAN_FRONTEND: "noninteractive"
        run: |
          sudo -E apt update
          sudo -E apt install -y cmake ninja-build patchelf libeatmydata1

      - name: Download scripts
        uses: actions/checkout@v2

      - name: Receive cache
        uses: actions/cache@v2
        with:
          path: build/llvm/stage1
          key: ${{ runner.os }}-stage1-${{ github.run_id }}

      - name: Build toolchain
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          LD_PRELOAD: "/usr/lib/x86_64-linux-gnu/libeatmydata.so"
        run: |
          ./build-toolchain.sh -s 2 &
          sleep 350m
          exit 0

      - name: Pass folder to next stage
        uses: actions/cache@v2
        with:
          # path: build/llvm/stage2
          path: build/llvm/
          key: ${{ runner.os }}-stage2-1-${{ github.run_id }}

  build-second-2:
    needs: build-second-1
    runs-on: ubuntu-latest
    steps:
      - name: Setup depends
        env:
          DEBIAN_FRONTEND: "noninteractive"
        run: |
          sudo -E apt update
          sudo -E apt install -y cmake ninja-build patchelf libeatmydata1

      - name: Download scripts
        uses: actions/checkout@v2

      - name: Receive cache from stage 1
        uses: actions/cache@v2
        with:
          path: build/llvm/stage1
          key: ${{ runner.os }}-stage1-${{ github.run_id }}

      - name: Receive cache from stage 2-1
        uses: actions/cache@v2
        with:
          path: build/llvm/
          key: ${{ runner.os }}-stage2-1-${{ github.run_id }}

      - name: Build toolchain
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          LD_PRELOAD: "/usr/lib/x86_64-linux-gnu/libeatmydata.so"
        run: ./build-toolchain.sh -s 2

      - name: Pass folder to next stage
        uses: actions/cache@v2
        with:
          path: build/llvm/stage2
          key: ${{ runner.os }}-stage2-2-${{ github.run_id }}

  build-third-1:
    needs: build-second-2
    runs-on: ubuntu-latest
    steps:
      - name: Setup depends
        env:
          DEBIAN_FRONTEND: "noninteractive"
        run: |
          sudo -E apt update
          sudo -E apt install -y cmake ninja-build patchelf libeatmydata1

      - name: Download scripts
        uses: actions/checkout@v2

      - name: Receive cache
        uses: actions/cache@v2
        with:
          path: build/llvm/stage2
          key: ${{ runner.os }}-stage2-2-${{ github.run_id }}

      - name: Build toolchain
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          LD_PRELOAD: "/usr/lib/x86_64-linux-gnu/libeatmydata.so"
        run: |
          ./build-toolchain.sh -s 3 &
          sleep 350m
          exit 0

      - name: Pass folder to next stage
        uses: actions/cache@v2
        with:
          path: build/llvm/stage3
          key: ${{ runner.os }}-stage3-1-${{ github.run_id }}

  build-third-2:
    needs: build-third-1
    runs-on: ubuntu-latest
    steps:
      - name: Setup depends
        env:
          DEBIAN_FRONTEND: "noninteractive"
        run: |
          sudo -E apt update
          sudo -E apt install -y cmake ninja-build patchelf zstd libeatmydata1

      - name: Download scripts
        uses: actions/checkout@v2


      - name: Receive cache from stage 2
        uses: actions/cache@v2
        with:
          path: build/llvm/stage2
          key: ${{ runner.os }}-stage2-2-${{ github.run_id }}

      - name: Receive cache from stage 3-1
        uses: actions/cache@v2
        with:
          path: build/llvm/stage3
          key: ${{ runner.os }}-stage3-1-${{ github.run_id }}

      - name: Build toolchain
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          LD_PRELOAD: "/usr/lib/x86_64-linux-gnu/libeatmydata.so"
        run: ./build-toolchain.sh -s 3

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "clang.tar.zst"
