name: Build & upload toolchain
on:
  push:
  schedule:
    # 3 PM PST on Saturdays
    - cron: '0 22 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download scripts
        uses: actions/checkout@v2

      - name: Deploy builder
        env:
          PACKET_TOKEN: ${{ secrets.PACKET_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKET_SSH_KEY: ${{ secrets.PACKET_SSH_KEY }}
          GIT_AUTHOR_NAME: 'github-actions'
          GIT_AUTHOR_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        run: |
          ci/build_agent.sh
