name: Build & upload toolchain
on:
  push:
  schedule:
    # 3 PM PST on Saturdays
    - cron: '0 22 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load libeatmydata
        run: echo "export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libeatmydata.so" | sudo tee -a /etc/profile
      - name: Setup clang
        env:
          DEBIAN_FRONTEND: "noninteractive"
        run: |
          sudo -E apt update
          sudo -E apt install -y cmake make ninja-build libelf-dev patchelf zstd libeatmydata1
          wget -q https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.zip
          unzip master.zip && rm master.zip
          sudo cp -r proton-clang-master/* /usr && rm -r proton-clang-master
        
      - name: Download scripts
        uses: actions/checkout@v2

      - name: Build toolchain
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: build-toolchain.sh -s 1

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "clang.tar.zst"
