name: Build & upload toolchain
on:
  push:
  schedule:
    # 3 PM PST on Saturdays
    - cron: '0 22 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup clang
        uses: egor-tensin/setup-clang@v1
        
      - name: Download scripts
        uses: actions/checkout@v2

      - name: Build toolchain
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          GIT_AUTHOR_NAME: "github-actions"
          GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        run: ci/build_agent.sh

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "clang.tar.zst"
